[server]
; db-pg-prd-01
; api-core-prd-01
; api-core-prd-02
; ci-runner-01
; db-maria-prd-01
; db-nosql-prd-01
; filer-01
; front-prd-01
; sftp-server
; tools-obs-01
glpi-pandora

[monitoring_storage_server]
filer-01
; mon-strg-home

[all:vars]
; Configuration variables for Alloy
alloy_version="1.5.1"
prometheus_remote_write_url="http://172.16.0.30:9090/api/v1/write"
loki_write_url="http://fw.si.unixo.fr:3100/loki/api/v1/push"
postgres_dsn="postgresql://monitor:ba46YbTeStbeKz@localhost:5432/postgres?sslmode=disable"
alloy_service="glpi"
env_type="prod"

; configuration variables for Loki
loki_version="2.9.0"
loki_port="3100"
loki_data_path="/DATA"

; Prometheus configuration variables
prometheus_version="2.50.0"
prometheus_port="9090"
node_exporter_port="9100"
prometheus_data_path="/DATA/prometheus/data"

; Thanos configuration variables
thanos_version="0.40.1"
thanos_query_port="9091"
prometheus_port="9090"
thanos_data_path="/DATA/thanos/data"

; Node exporter configuration variables
node_exporter_version="1.5.0"
node_exporter_port="9100"