[server]
proxmox-home
proxmox2-home
master-home
proxy-home
nextcloud-home
sftp-home
jenkins-home
ldap-home
debian-home
n8n-home
galaxyng-home
zigbee-home
mon-strg-home
database-home

[monitoring_storage_server]
mon-strg-home

[all:vars]
; Configuration variables for Alloy
alloy_version="1.5.1"
prometheus_remote_write_url="http://mon-strg.lxhome.local:9090/api/v1/write"
loki_write_url="http://mon-strg.lxhome.local:3100/loki/api/v1/push"

alloy_service="docker"
env_type="prod_lxhome"

; configuration variables for Loki
loki_version="2.9.0"
loki_port="3100"
loki_data_path="/"

; Prometheus configuration variables
; prometheus_version="2.50.0"
; prometheus_port="9090"
; node_exporter_port="9100"
; prometheus_data_path="/DATA/prometheus/data"

; Thanos configuration variables
; thanos_version="0.40.1"
; thanos_query_port="9091"
; prometheus_port="9090"
; thanos_data_path="/DATA/thanos/data"

; Node exporter configuration variables
; node_exporter_version="1.5.0"
; node_exporter_port="9100"