# --- Promtail ---
- name: Configure Promtail
  tags:
    - never
    - promtail
    - install_all
  block:
    - name: Download and extract Promtail
      ansible.builtin.unarchive:
        src: "{{ promtail_url }}"
        dest: "/opt/loki/"
        remote_src: true

    - name: Template Promtail config
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: "promtail.yml.j2", dest: "/opt/loki/promtail.yml" }
        - { src: "promtail.service.j2", dest: "/etc/systemd/system/promtail.service" }

    - name: Enable and start Promtail
      ansible.builtin.systemd:
        name: promtail
        enabled: true
        state: started
