---
alloy_url: https://github.com/grafana/alloy/releases/download/v{{ alloy_version }}/alloy-linux-amd64.zip
alloy_binary_path: /usr/local/bin/alloy-linux-amd64
alloy_binary_symlink_path: /usr/local/bin/alloy
