---
prometheus_version: "2.50.0"
prometheus_port: 9090
prometheus_url : "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_data_path: "/opt/prometheus/data"